// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NivelAccesDate_CodeFirst.Data;

#nullable disable

namespace NivelAccesDate_CodeFirst.Migrations
{
    [DbContext(typeof(ConversionsDbContext))]
    [Migration("20260112122142_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Models.Conversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ImageIdFrom")
                        .HasColumnType("int")
                        .HasColumnName("imageId_from");

                    b.Property<int>("ImageIdTo")
                        .HasColumnType("int")
                        .HasColumnName("imageId_to");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("ImageIdFrom");

                    b.HasIndex("ImageIdTo");

                    b.HasIndex("UserId");

                    b.ToTable("conversions", (string)null);
                });

            modelBuilder.Entity("CodeFirst.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("format");

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("md5");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("path");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("CodeFirst.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Limit")
                        .HasColumnType("int")
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Limit = 10,
                            Name = "Free",
                            Price = 0
                        },
                        new
                        {
                            Id = 2,
                            Limit = 1000,
                            Name = "Enterprise",
                            Price = 10
                        },
                        new
                        {
                            Id = 3,
                            Limit = 1000,
                            Name = "Premium",
                            Price = 20
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("planId");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CodeFirst.Models.Conversion", b =>
                {
                    b.HasOne("CodeFirst.Models.Image", "ImageFrom")
                        .WithMany("ConversionsFrom")
                        .HasForeignKey("ImageIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.Image", "ImageTo")
                        .WithMany("ConversionsTo")
                        .HasForeignKey("ImageIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.User", "User")
                        .WithMany("Conversions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImageFrom");

                    b.Navigation("ImageTo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeFirst.Models.User", b =>
                {
                    b.HasOne("CodeFirst.Models.Plan", "Plan")
                        .WithMany("Users")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_users_plans");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CodeFirst.Models.Image", b =>
                {
                    b.Navigation("ConversionsFrom");

                    b.Navigation("ConversionsTo");
                });

            modelBuilder.Entity("CodeFirst.Models.Plan", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CodeFirst.Models.User", b =>
                {
                    b.Navigation("Conversions");
                });
#pragma warning restore 612, 618
        }
    }
}
